"""Initial migration

Revision ID: 9c8e802b8c58
Revises: 
Create Date: 2025-11-27 01:29:53.467752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8e802b8c58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('manufacturer_id', sa.String(), nullable=True),
    sa.Column('product_metadata', sa.JSON(), nullable=True),
    sa.Column('dkg_ual', sa.String(), nullable=True),
    sa.Column('registration_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'WARNING', 'FRAUD_RISK', name='productstatus'), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('handler_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('ai_results', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('ai_results',
    sa.Column('ai_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('validation_output', sa.JSON(), nullable=True),
    sa.Column('anomaly_output', sa.JSON(), nullable=True),
    sa.Column('fraud_output', sa.JSON(), nullable=True),
    sa.Column('trust_score_delta', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('ai_id')
    )
    op.create_table('handlers',
    sa.Column('handler_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('handler_id')
    )
    op.create_table('batches',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('manufacturer_id', sa.String(), nullable=True),
    sa.Column('batch_metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_table('feedback')
    op.drop_table('batches')
    op.drop_table('handlers')
    op.drop_table('ai_results')
    op.drop_table('events')
    op.drop_table('products')
    # ### end Alembic commands ###
